<!doctype html>
<!--app template-->
<html lang="en" ng-app="SparkApp" id="ng-app">
<head>
	<!--install firebase-->
	<script src='https://cdn.firebase.com/v0/firebase.js'></script>
	<script type='text/javascript' src='https://cdn.firebase.com/v0/firebase-simple-login.js'></script>
	<!--set the meta character to utf-8 b/c I'm using special characters-->
	<meta charset=”utf-8”> 
	<!--enable the bootstrap grid system-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Spark</title>
	<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script type="text/javascript" src="js/angular.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link rel="stylesheet" href="css/bootstrap-responsive.min.css">
	
	<script type="text/javascript" src="js/spark-app/app.js"></script>
	<script type="text/javascript" src="js/spark-app/controllers/mainController.js"></script>
	<link rel="stylesheet" href="css/main.css">
    <script src="js/project.js"></script>
</head>

<body>
	
	<!-- -->
	<div class='banner'>
        <div class='container'>
         <img src="img/sparklogo_330x60.png" class="img-responsive" />
        </div>
    </div>